services:
  - type: web
    name: restaurant-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_final.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    plan: free
